language: node_js
node_js:
- '8'
- '11'
- stable
install:
- npm install
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: thomas@toye.io
  api_key:
    secure: gnPx6zRpHUdNf6uJ3LL+Ra5oB1LqtiKYQ7RV87NCC1EHCL5D3JsSR02/opj35L8TdfRsYkfIARTYmO9hEpns0qYwYxokJ50rHgrZQ4PepTWteqwU32VG5gJm3jwn3lBrtdJZRxZ21jvN2cmEBnhGD9HiANrnm+BqH9kma0C4d+Y3+dcMN+NUN3IkhaPcGNnt4qSrjw1oG2MpmHP/uBsq/dgBn7o/9jKO2Us1G6X3fWGhyRBqtdy0esP5qZcDPsqwgv3cot/HhtI3F34CGLcYq3EmkyDXw0m0ZHUbM96Zug7NN3Ap7l6RspXw9tbBSRmlu+ActGqNFQt3/hCJItCJHmyWly1Mbz7OLH1ePfZOBIwbpgaamJt8GDUHBd7WeVSgaEAyLeQhpvnQNytRMsI4rhLv4yf952yeMcGKIxhEBv1w1vh0zADcKYutDHED98SBDoWxbPpeBWB2jICei9TnKJ8cWV9E1aTxCxAYCJGQsAD54m07ZjQNCsm4Aio3npTBavAYtif1tb5BGtLNAUnmlqKwClsF6Er54W2W5xUj6UlRVAsHH/qMvFKV1O/NonOMk9mLEkfvTnICGGb8cA1M1uqdlqmMqG+7IILS5KNtsQNYkMLbcUM3BByTc+A1YsQzz5h4iLxEFAnsT3jK3Rzqd53D9e72sgzUzbQntzJylog=
  skip_cleanup: true
  on:
    tags: true
    repo: speelpleinwerking-com/example-data
